export const project_details = [
  {
    id: 1,
    name: 'Airflow Data Pipeline - In Development',
    link: [
      '/in-development?project=airflow',
    ],
    type: 'airflow',
    github_link: 'https://github.com/jeffieee',
  },
  {
    id: 2,
    name: 'Grafana Monitoring Dashboard - In Development',
    link: [
      '/in-development?project=grafana',
    ],
    type: 'grafana',
    github_link: 'https://github.com/jeffieee',
  },
  {
    id: 3,
    name: 'CityAssist: Local Resident Monitoring and Demographic-Based Program Recommendation System',
    link: [
      '1YNSdJceEyLU5wwyZi3a7Rc38sufTdlZu',
      '1vxqP_rZ3K-U1sbAl5BITdK3vHs0jfXGI',
      '18zf8_ot7D3mtqTV7_x-mHJC-h9n8tewx',
      '1b8P449NrhIRhKCJsTJpCWYu_h05tF_-C',
      '1UsDPu8tNUDHuN755tx3cb1N12UoQnea0',
      '1JdRda2o4msOqVpXpLxMIi0zENnRi7Ojq',
      '1DlFIRgJlLtSODwpXOYzvva3Bi4gfEtXz',
      '1t5YyteoVL17VNTNCFcx0wxLjYAQNiCMr',
      '1VdQuYVbE_niDDaP1HGq-wkd-JRYH_vbP',
      '1Yus1F_IKK_3_NmfuMAD1GiIyM0NTygqB',
    ],
    type: 'web',
    github_link: 'https://github.com/cocokhyle/DataDriven',
  },
  {
    id: 4,
    name: 'Web-Based Student Academic Performance Monitoring System for Banay-Banay Elementary School',
    link: [
      '1fJPClRSSf2-biD5ucry2-Ddn6JR3n0QY',
      '16IvGObUG7z-MfZAdIxsHaS82HICmq9k3',
      '1FAHddPz62BW6rU129UFjBRd3d0E15ZNr',
      '1IOSITKPXfIKiO_JdJVgi56KHERQpHV03',
      '1j5ibk9zE9wXhi98pdy9Fo1VR-pd1SPVo',
      '1cS1zEWlZYjjhcZMmaaqFAr0IZCoCZE3H',
    ],
    type: 'web',
    github_link: 'https://github.com/jeffieee/My-Projects/blob/66a6c4ee6f056c0c5780781fa12cf9b96973adf7/README.md',
  },
  {
    id: 5,
    name: 'BayaScript: Convolutional Neural Networks Driven Character Recognition In a Mobile Application for Learning BayBayin',
    link: [
      '1TKlxOKQNZkazynes-OaYzz64IqmR3_9V',
      '1TIseFzb9hPCH6JX4ynf98qaLyA0w5s6U',
      '1SZ_p2ToiG5Vh68pAbX5-w8V7XiMH_ARC',
      '1SvMK7IhqZjOE3ON25BH4r5R1my1PdxSr',
      '1SroNQMPs5Ut8sUuSek8irC_fQNneS2MV',
      '1StBtrnXigAnCYgVhChpCPur3PnzrIpv3',
      '1TByPXzCRXvXp_JnhzWfJubT-sA545DAj',
      '1SkYKuoH0D6Eg9Gz6WQ7Qv2yVf0rZOk-p',
      '1Sfjhv3Xvk07cnd4v0iMPljPUWtEPWVwS',
      '1SfCMWwDjFuqT5aB6AWGJlEBqxvlB6uWh',
      '1TDtF3yTjsZP86cvMdtRjE8z46sKX2UHu',
      '1SGcFT_AptB--5chVyVU1K66BTFvu7gpS',
      '1STKxA1ZhIh_zrmHDdfJzVu8WMDGa8Akp',
      '1SBZjVbbWdH22jTOKwBTgDAWOMWY1QIOW',
    ],
    type: 'mobile',
    github_link: 'https://github.com/jeffieee/My-Projects/blob/6be6e8515f639191dcf9e1639eae90423b0fb31f/README.md',
  },
];
